# Generated by Django 4.0.4 on 2022-05-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_cadeira_professor_projeto_cadeira_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadeira',
            name='ano_letivo',
        ),
    ]
