# Generated by Django 4.0.4 on 2022-05-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_cadeira_ano_letivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
