# Generated by Django 4.0.4 on 2022-05-29 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_professor_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Cadeiras', to='portfolio.professor'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='cadeira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Projetos', to='portfolio.cadeira'),
        ),
    ]
