# Generated by Django 4.0.4 on 2022-05-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_cadeira_professor_alter_projeto_cadeira'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
