# Generated by Django 4.0.4 on 2022-05-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_cadeira_imagem_alter_professor_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='ects',
            field=models.IntegerField(default=1),
        ),
    ]
