# Generated by Django 4.0.4 on 2022-05-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_cadeira_ects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/static/portfolio/images/cadeira'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/static/portfolio/images/professores'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/static/portfolio/images/projetos'),
        ),
    ]
