# Generated by Django 4.0.4 on 2022-06-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_cadeira_nome_alter_cadeira_topicos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descricao',
            field=models.TextField(),
        ),
    ]
