# Generated by Django 4.0.4 on 2022-06-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_alter_post_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='ano',
            field=models.IntegerField(default=2020),
        ),
    ]
